plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "vue-cli-plugin-vuetify@*":
    dependencies:
      "webpack": "^4.44.2"
  "eslint-import-resolver-webpack@*":
    dependencies:
      "webpack": "^4.44.2"
  "vue-jest@*":
    dependencies:
      "vue": "^2.6.11"
      "vue-template-compiler": "^2.6.11"
      "convert-source-map": "^1.4.0"
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": "^7.1.0"
