compressionLevel: 0

enableGlobalCache: false

enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

packageExtensions:
  "@pinia/testing@*":
    peerDependencies:
      vue: "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "@vue/server-renderer": "*"
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/integrations@*":
    peerDependencies:
      vue: "*"
  "@vueuse/router@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  splitpanes@*:
    dependencies:
      vue: "*"

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - arm64-musl
  os:
    - linux
    - darwin
  libc:
    - musl

plugins:
  - checksum: b635163d641034738b2dc4b704a834ae1d0594b1b7f9f0b93f70c7f2e1617d4ba407e25606abb6fbd19de1dc94fa13414aa26037adbf35b372c6b1f56009860f
    path: .yarn/plugins/plugin-prod-install.cjs
    spec: "https://gist.githubusercontent.com/holgerkoser/e1cb865214c9d4e9f579b3fc0644451b/raw/cdc353c851c887b141130e5a33b481d3709941a0/plugin-prod-install.cjs"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
