changesetBaseRefs:
- "master"
- "origin/master"
- "hotfix-1.66"
- "origin/hotfix-1.66"

enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

packageExtensions:
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@vue/cli-plugin-unit-jest@*":
    dependencies:
      semver: "*"
  "@vue/cli-service@*":
    dependencies:
      "@babel/core": "*"
      "@vue/compiler-sfc": "*"
  "@vue/eslint-config-standard@*":
    dependencies:
      webpack: ^5.0.0
  vue-eslint-parser@*:
    dependencies:
      "@babel/core": "*"
      "@babel/eslint-parser": "*"
  "@gardener-dashboard/backend@*":
    dependencies:
      "openapi-types": "*"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/holgerkoser/yarn-contrib/-/raw/1.0.0-beta.3/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-3.2.1.cjs
