compressionLevel: 0

enableGlobalCache: false

enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard
  - code: YN0086
    level: discard

packageExtensions:
  "@pinia/testing@*":
    peerDependencies:
      vue: "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "@vue/server-renderer": "*"
    peerDependencies:
      vue: "*"
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/integrations@*":
    peerDependencies:
      vue: "*"
  "@vueuse/router@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-alias: "*"

plugins:
  - path: .yarn/plugins/plugin-prod-install.cjs

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - arm64-musl
  libc:
    - musl
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.6.0.cjs
