compressionLevel: 0

enableGlobalCache: false

enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

packageExtensions:
  "@pinia/testing@*":
    peerDependencies:
      vue: "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "@vue/server-renderer": "*"
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/integrations@*":
    peerDependencies:
      vue: "*"
  "@vueuse/router@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  splitpanes@*:
    dependencies:
      vue: "*"

plugins:
  - checksum: 32461aed30ff121821fa68d0309c3f481e8291611105c423a5158e305e68eed28a1de4318f891c095b92e62ba003389bdebda317e5900327e920c9c67a4b2fc6
    path: .yarn/plugins/plugin-prod-install.cjs
    spec: scripts/plugin-prod-install.cjs

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - arm64-musl
  libc:
    - musl
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.0.2.cjs
