changesetBaseRefs:
- "master"
- "origin/master"
- "hotfix-1.70"
- "origin/hotfix-1.70"

enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

packageExtensions:
  "@pinia/testing@*":
    peerDependencies:
      vue: "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "@vue/server-renderer": "*"
  "@vueuse/core@*":
    peerDependencies:
      vue: "*"
  "@vueuse/integrations@*":
    peerDependencies:
      vue: "*"
  "@vueuse/router@*":
    peerDependencies:
      vue: "*"
  "@vueuse/shared@*":
    peerDependencies:
      vue: "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  splitpanes@*:
    dependencies:
      vue: "*"
  vite-plugin-vuetify@*:
    peerDependencies:
      vue: "*"
  vite@*:
    dependencies:
      "@esbuild/linux-arm64": "0.18"
      "@esbuild/linux-x64": "0.18"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/holgerkoser/yarn-contrib/-/raw/1.0.0-beta.3/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.6.3.cjs
