enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

packageExtensions:
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@octokit/rest@*":
    dependencies:
      "@octokit/core": "*"
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-eslint": "*"
      "@vue/cli-plugin-router": "*"
      "@vue/cli-plugin-unit-jest": "*"
      "@vue/cli-plugin-vuex": "*"
      vue-cli-plugin-vuetify: "*"
  eslint-import-resolver-webpack@*:
    dependencies:
      webpack: ^4.44.2
  vue-cli-plugin-vuetify@*:
    dependencies:
      webpack: ^4.44.2
  vue-eslint-parser@*:
    dependencies:
      babel-eslint: "*"
  vue-jest@*:
    dependencies:
      convert-source-map: "*"
      vue: "*"
      vue-template-compiler: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/holgerkoser/yarn-contrib/-/raw/1.0.0-beta.3/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
