# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

enableTelemetry: false

enableTransparentWorkspaces: false

packageExtensions:
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": ^7.1.0
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-babel": ~4.5.0
      "@vue/cli-plugin-eslint": ~4.5.0
      "@vue/cli-plugin-router": ~4.5.0
      "@vue/cli-plugin-unit-jest": ~4.5.0
      "@vue/cli-plugin-vuex": ~4.5.0
      vue-cli-plugin-vuetify: ~2.0.7
  eslint-import-resolver-webpack@*:
    dependencies:
      webpack: ^4.44.2
  vue-cli-plugin-vuetify@*:
    dependencies:
      webpack: ^4.44.2
  vue-eslint-parser@*:
    dependencies:
      babel-eslint: ^10.1.0
  vue-jest@*:
    dependencies:
      convert-source-map: ^1.4.0
      vue: ^2.6.11
      vue-template-compiler: ^2.6.11

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/holgerkoser/yarn-contrib/-/raw/1.0.0-beta.2/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

logFilters:
  - code: "YN0005"
    level: "discard"