packageExtensions:
  "@babel/plugin-syntax-jsx@*":
    dependencies:
      "@babel/core": ^7.1.0
  eslint-import-resolver-webpack@*:
    dependencies:
      webpack: ^4.44.2
  vue-cli-plugin-vuetify@*:
    dependencies:
      webpack: ^4.44.2
  vue-jest@*:
    dependencies:
      convert-source-map: ^1.4.0
      vue: ^2.6.11
      vue-template-compiler: ^2.6.11

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
