#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

echo "Check Docforge Manifest"

docforgeVersion="v0.21.0"
docCommitHash="12922abea4c5afa207cc9c09b18414cd2348890c"

repoPath="$(readlink -f $(dirname ${0})/..)"
manifestPath="${repoPath}/.docforge/manifest.yaml"
diffDirs=".docforge/;docs/"

if [[ ! -d ${repoPath}/scripts/bin ]]; then
  mkdir -p ${repoPath}/scripts/bin
fi

docforgeBinPath="${repoPath}/scripts/bin/docforge"
export PATH=${repoPath}/scripts/bin:$PATH
if [[ ! -f "${docforgeBinPath}" || $(${docforgeBinPath} version) != "${docforgeVersion}" ]]; then
  # Installing docforge
  curl -L -o "${docforgeBinPath}" https://github.com/gardener/docforge/releases/download/${docforgeVersion}/docforge-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m | sed 's/x86_64/amd64/')
  chmod +x ${docforgeBinPath}
fi

tmpDir=$(mktemp -d)
function cleanup {
    rm -rf "$tmpDir"
}
trap cleanup EXIT ERR INT TERM

curl https://raw.githubusercontent.com/gardener/documentation/${docCommitHash}/.ci/check-manifest --output ${tmpDir}/check-manifest-script.sh && chmod +x ${tmpDir}/check-manifest-script.sh
curl https://raw.githubusercontent.com/gardener/documentation/${docCommitHash}/.ci/check-manifest-config --output ${tmpDir}/manifest-config
scriptPath="${tmpDir}/check-manifest-script.sh"
configPath="${tmpDir}/manifest-config"

${scriptPath} --repo-path ${repoPath} --repo-name "dashboard" --use-token false --manifest-path ${manifestPath} --diff-dirs ${diffDirs} --config-path ${configPath}
