#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

docforgeVersion="v0.32.0"
docCommitHash="7709601d0ce25e21c8b68dd6a2de91a326b9d41d"

echo "> Check Docforge Manifest"
repoPath=${1-"$(readlink -f "$(dirname "${0}")/..")"}
manifestPath=${2-"${repoPath}/.docforge/manifest.yaml"}
diffDirs=${3-".docforge/;docs/"}
repoName=${4-"dashboard"}
useToken=${5-false}

docforgeBinPath="${repoPath}/scripts/bin/docforge"
export PATH=${repoPath}/scripts/bin:$PATH

if [[ ! -d ${repoPath}/scripts/bin ]]; then
  mkdir -p ${repoPath}/scripts/bin
fi

if [[ ! -f "${docforgeBinPath}" || $(${docforgeBinPath} version) != "${docforgeVersion}" ]]; then
  # Installing docforge
  curl -L -o "${docforgeBinPath}" https://github.com/gardener/docforge/releases/download/${docforgeVersion}/docforge-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m | sed 's/x86_64/amd64/')
  chmod +x ${docforgeBinPath}
fi

tmpDir=$(mktemp -d)
function cleanup {
    rm -rf "$tmpDir"
}
trap cleanup EXIT ERR INT TERM

curl https://raw.githubusercontent.com/gardener/documentation/${docCommitHash}/.ci/check-manifest --output "${tmpDir}/check-manifest-script.sh" && chmod +x "${tmpDir}/check-manifest-script.sh"
curl https://raw.githubusercontent.com/gardener/documentation/${docCommitHash}/.ci/check-manifest-config --output "${tmpDir}/manifest-config"
scriptPath="${tmpDir}/check-manifest-script.sh"
configPath="${tmpDir}/manifest-config"

${scriptPath} --repo-path "${repoPath}" --repo-name "${repoName}" --use-token "${useToken}" --manifest-path "${manifestPath}" --diff-dirs "${diffDirs}" --config-path "${configPath}"