#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f $(dirname ${0})/..)"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

cd "${SOURCE_PATH}"

# Abort with an error exit code if
# the lockfile was to be modified or
# the cache folder was to be modified or
# the checksums of the packages are not consistent
yarn install --immutable --immutable-cache --check-cache

# Install helm
VERSION="3.11.1"
BASE_URL="https://get.helm.sh"
case `uname -m` in
  x86_64) ARCH=amd64; ;;
  aarch64) ARCH=arm64; ;;
  *) echo "un-supported arch, exit ..."; exit 1; ;;
esac
apk add --update --no-cache wget
wget ${BASE_URL}/helm-v${VERSION}-linux-${ARCH}.tar.gz -O - | tar -xz
mv linux-${ARCH}/helm /usr/bin/helm
chmod +x /usr/bin/helm
rm -rf linux-${ARCH}

# Run the helm chart unit tests
yarn workspace @gardener-dashboard/charts run test
