#!/usr/bin/env sh

set -e

if [ -z "${REPO_DIR}" ]; then
  export REPO_DIR="$(readlink -f $(dirname ${0})/..)"
else
  export REPO_DIR="$(readlink -f "${REPO_DIR}")"
fi

# not every environment has pushd
old_pwd=$PWD
cd "${REPO_DIR}"

if [ -z "${EFFECTIVE_VERSION}" ]; then
    version="$(cat "${REPO_DIR}/VERSION")"
    if [ -z "${version}" ]
    then
      echo "Version not found"
      exit 1
    fi
else
    version="${EFFECTIVE_VERSION}"
fi

# install jq if absent
if ! which jq > /dev/null; then
    apk update
    apk add jq
fi

# update version in json file
update_version () {
  dirname="$1"
  fname="$2"
  temp_dir=$(mktemp -d)
  jq '.version = $version' --arg version "${version}" "${dirname}/${fname}" > "${temp_dir}/${fname}" && mv "${temp_dir}/${fname}" "${dirname}/${fname}"
  rm -rf "${temp_dir}"
  echo "updated version in file ${dirname}/${fname}"
}

# bump backend version
update_version "${REPO_DIR}/backend" "package.json"
update_version "${REPO_DIR}/backend" "package-lock.json"

# bump frontend version
update_version "${REPO_DIR}/frontend" "package.json"
update_version "${REPO_DIR}/frontend" "package-lock.json"

cd "${old_pwd}"
