#!/usr/bin/env sh

set -e

if [ -z "$REPO_DIR" ]; then
  export REPO_DIR="$(readlink -f $(dirname ${0})/..)"
else
  export REPO_DIR="$(readlink -f "${REPO_DIR}")"
fi

# not every environment has pushd
old_pwd=$PWD
cd "${REPO_DIR}"

if [ -z "$EFFECTIVE_VERSION" ]; then
    version="$(cat "${REPO_DIR}/VERSION")"
    if [ -z "$version" ]
    then
      echo "Version not found"
      exit 1
    fi
else
    version="${EFFECTIVE_VERSION}"
fi

# revert changed VERSION
git checkout "${REPO_DIR}/VERSION"

# print environment
env

# install npm if absent
if ! which npm > /dev/null; then
    apk update
    apk add npm
fi

# bump backend version
sed -i -r "s/\"version\": *\".+\"/\"version\": \"$version\"/g" "${REPO_DIR}/backend/package.json"
npm i --prefix "${REPO_DIR}/backend"
# bump frontend version
sed -i -r "s/\"version\": *\".+\"/\"version\": \"$version\"/g" "${REPO_DIR}/frontend/package.json"
npm i --prefix "${REPO_DIR}/frontend"

cd "${old_pwd}"
