#!/usr/bin/env sh

set -e

if [ -z "$SOURCE_PATH" ]; then
  export SOURCE_PATH="$(readlink -f $(dirname ${0})/..)"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

# not every environment has pushd
old_pwd=$PWD

# Dashboard backend
cd "${SOURCE_PATH}/backend"
npm install
npm run -s lint
npm run -s test-cov

# Dashboard frontend
cd "${SOURCE_PATH}/frontend"
npm install
npm run -s lint
npm run -s unit

cd "${old_pwd}"

