#!/bin/sh

# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Install required tools on alpine
install_if_missing() {
  # usage: install_if_missing <cmd_name> <apk_package_name>
  CMD_NAME="$1"
  APK_PKG="$2"

  if ! command -v "$CMD_NAME" >/dev/null 2>&1; then
    echo "Command '$CMD_NAME' not found."
    if [ -f /etc/alpine-release ]; then
      echo "Installing '$APK_PKG' on Alpine..."
      apk add --no-cache "$APK_PKG"
    else
      echo "'$APK_PKG' not found, but this is not an Alpine image. Skipping..."
    fi
  fi
}

# Install make if it does not exist
install_if_missing make make

make verify
