#!/bin/sh

# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o pipefail
set -e

# For the verify step concourse will set the following environment variables:
# MAIN_REPO_DIR - path to the main repository

if [[ -z "${MAIN_REPO_DIR}" ]]; then
  export MAIN_REPO_DIR="$(readlink -f "$(dirname ${0})/..")"
else
  export MAIN_REPO_DIR="$(readlink -f ${MAIN_REPO_DIR})"
fi

cd "${MAIN_REPO_DIR}"

# Install required tools on alpine
install_if_missing() {
  # usage: install_if_missing <cmd_name> <apk_package_name>
  CMD_NAME="$1"
  APK_PKG="$2"

  if ! command -v "$CMD_NAME" >/dev/null 2>&1; then
    echo "Command '$CMD_NAME' not found."
    if [ -f /etc/alpine-release ]; then
      echo "Installing '$APK_PKG' on Alpine..."
      apk add --no-cache "$APK_PKG"
    else
      echo "'$APK_PKG' not found, but this is not an Alpine image. Skipping..."
    fi
  fi
}

install_if_missing make make
install_if_missing helm helm

# Abort with an error exit code if
# the lockfile was to be modified or
# the cache folder was to be modified or
# the checksums of the packages are not consistent
yarn install --immutable --immutable-cache --check-cache

# Run the helm chart unit tests
yarn workspace @gardener-dashboard/charts run test

# Run linting
if [ "${SARIF+no}" = yes ] ; then
  # supposed to be run in release jobs
  make lint-sarif
else
  make lint
fi

# Run tests
make test-cov
