name: Prepare Release

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: bump-version
      shell: bash
      run: |
        set -eu
        git fetch origin master
        export HUSKY=0 # disable husky-hooks
        .ci/bump_version
