name: Prepare Release

runs:
  using: composite
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: '24.14.0'
    - name: bump-version
      shell: bash
      run: |
        set -eu
        git fetch origin master
        export HUSKY=0 # disable husky-hooks
        .ci/bump_version
