name: Prepare Release

runs:
  using: composite
  steps:
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: '22.22.0'
    - name: bump-version
      shell: bash
      run: |
        set -eu
        git fetch origin master
        export HUSKY=0 # disable husky-hooks
        .ci/bump_version
