#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

COMMIT=$(git rev-parse --short HEAD)

TAG=$(git describe --exact-match --abbrev=0 --tags ${COMMIT} 2> /dev/null || true)

if [ -z "$TAG" ]
then
    VERSION=$COMMIT
else
    VERSION=$TAG
fi

if [ -n "$(git diff --shortstat 2> /dev/null | tail -n1)" ]
then
    VERSION="${VERSION}-dirty"
fi

echo $VERSION
