#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

# change current working directory
WORK_DIR=${PWD}
REPO_DIR="$(readlink -f $(dirname ${0})/..)"
# relative path to workspace
WORKSPACE=$(sed -r 's/^\/(frontend|backend|charts|packages\/[^/]*)\/.*/\1/g' <<< ${1#${REPO_DIR}})
cd "${REPO_DIR}/${WORKSPACE}"
# run test of workspace directory
yarn test "$@"
# restore previous working directory
cd "${WORK_DIR}"