apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: daffodil
  namespace: garden-flowering
spec:
  credentialsBindingName: trial-credentials-gcp
  cloudProfile:
    kind: CloudProfile
    name: gcp
  region: europe-west1
  purpose: evaluation
  provider:
    type: gcp
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      networks:
        workers: 10.250.0.0/16
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      zone: europe-west1-c
      kind: ControlPlaneConfig
    workers:
    - name: cpu-worker
      maximum: 2
      minimum: 1
      maxSurge: 1
      maxUnavailable: 0
      machine:
        type: n1-standard-2
        image:
          name: gardenlinux
      volume:
        type: pd-standard
        size: 50Gi
      zones:
        - europe-west1-c
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.250.0.0/16
    services: 100.64.0.0/13
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  hibernation:
    enabled: true
    schedules:
      - start: '00 17 * * 1,2,3,4,5'
        location: Europe/Kiev
  kubernetes:
    allowPrivilegedContainers: true
    kubeControllerManager:
      nodeCIDRMaskSize: 24
    kubeProxy:
      mode: IPTables
    version: 1.18.3
  addons:
    nginxIngress:
      enabled: false
    kubernetesDashboard:
      enabled: false
