name: Zizmor Workflow Lint

on:
  push:
    branches:
    - master
    - hotfix-*
    paths:
    - '.github/**'
  pull_request:
    paths:
    - '.github/**'

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          # renovate: datasource=github-releases depName=zizmorcore/zizmor
          version: 1.26.1
          min-severity: low
          min-confidence: low
          advanced-security: false
          annotations: true
