name: Zizmor Workflow Lint

on:
  push:
    branches:
    - master
    - hotfix-*
    paths:
    - '.github/**'
  pull_request:
    paths:
    - '.github/**'

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          # renovate: datasource=github-releases depName=zizmorcore/zizmor
          version: 1.26.1
          min-severity: low
          min-confidence: low
          advanced-security: false
          annotations: true
